### ISSUE TITLE
ImportError: No module named 'six'

### ISSUE THREAD

**Issue by konius** [enginespot/js-beautify-sublime#39] opened 2015-12-10 14:54 UTC
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "jsbeautify in /Users/User1/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package", line 115, in run
  File "jsbeautify in /Users/User1/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package", line 190, in format_whole_file
  File "/Users/User1/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 237, in beautify
  File "/Users/User1/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 315, in __init__
  File "/Users/User1/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 157, in __init__
ImportError: No module named 'six'

**Comment by Koleok** [comment] 2015-12-10 16:14
Same, just started today after using this seamlessly for months

**Comment by bolgovr** [comment] 2015-12-10 16:32
+1

**Comment by Koleok** [comment] 2015-12-10 16:48
It is eye opening how much I depend on this haha

**Comment by danmt** [comment] 2015-12-11 04:09
+1

**Comment by sahilnarain** [comment] 2015-12-11 18:42
+1! I've become overly dependent on this too!

**Comment by sahilnarain** [comment] 2015-12-11 18:45
I'm overly dependent on this!!! +1.

**Comment by sahilnarain** [comment] 2015-12-11 18:47
+1, this was working perfectly fine till a few hours ago!

**Comment by xenomuta** [comment] 2015-12-11 18:48
+1
How can we install it to sublime from repo?

**Comment by fyelles** [comment] 2015-12-11 21:15
while they fix it. You can add a new repo from https://github.com/fyelles/js-beautify-sublime and install the package again. ( I remove the latest commit from my fork)

**Comment by maaaaarco** [comment] 2015-12-14 14:51
Same here :(

**Comment by booleanbetrayal** [comment] 2015-12-14 19:58
oww ...

**Comment by ioncube** [comment] 2015-12-14 23:53
Thanks @fyelles for the fork, got us working again; can't live without it :)

**Comment by mattblang** [comment] 2015-12-15 17:28
Thanks @fyelles ! I removed the original package, did a `git clone` of your fork in `/Users/{user}/Library/Application Support/Sublime Text 3/Packages`, then everything was good!

**Comment by cromestant** [comment] 2015-12-16 22:01
+1 issue happening

**Comment by Koleok** [comment] 2015-12-16 23:20
Thanks also @fyelles i was able to get back to work using your suggestion :)

**Comment by ioncube** [comment] 2015-12-17 16:47
Having used @fyelles fork with surpirising ease, here's how for anyone that might otherwise take an unnecessarily more complex alternative.

1. Select Package Control and then Add Repository
2. Copy/Paste/Enter the URL https://github.com/fyelles/js-beautify-sublime to add the repo
3. Select Package Control and now remove Javascript beautify
4. Finally, select Package Control and add Javascript beautify, making sure it shows that it's coming from the fyelles link. That's it! 

The first time I did this the package showed up twice when adding and I made sure to select the correct one; doing it again just now on a different machine it only showed the fyelles one, but that's just fine :)

**Comment by cromestant** [comment] 2015-12-17 17:07
This is all great but maybe the PR should just be merged

On Thursday, December 17, 2015, ioncube <notifications@github.com> wrote:

> Having used @fyelles <https://github.com/fyelles> fork with surpirising
> ease, here's how for anyone that might otherwise take an unnecessarily more
> complex alternative.
>
>    1. Select Package Control and then Add Repository
>    2. Copy/Paste/Enter the URL
>    https://github.com/fyelles/js-beautify-sublime to add the repo
>    3. Select Package Control and now remove Javascript beautify
>    4. Finally, select Package Control and add Javascript beautify, making
>    sure it shows that it's coming from the fyelles link. That's it!
>
> The first time I did this the package showed up twice when adding and I
> made sure to select the correct one; doing it again just now on a different
> machine it only showed the fyelles one, but that's just fine :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enginespot/js-beautify-sublime/issues/39#issuecomment-165506343>
> .
>


-- 
MSc. Charles M. Romestant F.


Merci de penser à l'environnement avant d'imprimer cet e-mail
Please think about the environment before you print this e-mail
Por favor piense en el medio ambiente antes de imprimir este e-mail

**Comment by endquote** [comment] 2015-12-19 03:23
Can't seem to get it to install in ST 3083 Mac, the enginespot module always wins over the fyelles one even after adding the repo to package control.

**Comment by endquote** [comment] 2015-12-19 19:34
Ok, actually @ioncube 's instructions do work, but when you install the new one, the title is "js-beautify-sublime", not "JavaScript Beautify".

**Comment by ioncube** [comment] 2015-12-21 10:15
@endquote in the package control list it's js-beautify-sublime, but in the Package Settings it still says Javascript Beautify for me, and the setting and key bindings under that name still work (I bound it to ctrl-f12). Maybe depends on platform or other things but at least it works :)

**Comment by GISDev01** [comment] 2015-12-22 20:11
Full steps to fix (incorporates 2 separate comments above):

    Select Package Control and then Add Repository
    Copy/Paste/Enter the URL: https://github.com/fyelles/js-beautify-sublime and hit enter
    Select Package Control and Remove Package: Javascript beautify
    Select Package Control and Install Package (Note Different Name): js-beautify-sublime

**Comment by manmorjim** [comment] 2015-12-22 23:35
Ok, @GISDev01 's steps work for me. Thank you all :smile:

**Comment by leguano** [comment] 2015-12-23 15:03
works fine. thank you!

**Comment by zhaiduo** [comment] 2015-12-30 05:00
still not work:
```
File "/Users/admin/Library/Application Support/Sublime Text 3/Installed Packages/Javascript Beautify.sublime-package/libs/js-beautify/python/jsbeautifier/__init__.py", line 157, in __init__
ImportError: No module named 'six'
```

**Comment by zhaiduo** [comment] 2015-12-30 05:02
it works, thanks @GISDev01

**Comment by ilovett** [comment] 2015-12-31 20:25
:+1:

**Comment by nfantone** [comment] 2015-12-31 21:05
Works like a charm. But I think we all agree that this should really be made into a PR.

**Comment by wmigas** [comment] 2016-01-13 18:06
It is caused by bug in js-beatify https://github.com/beautify-web/js-beautify/issues/465

**Comment by denysvitali** [comment] 2016-01-13 18:22
+1 @fyless fix worked for me

**Comment by cromestant** [comment] 2016-01-13 20:38
I confirm the fix works, but would love to see the merged into a PR.
however it does not seem like it is actively looked at, for the time being
I 'll use , as the others, the alternative package.
thanks

On Wed, Jan 13, 2016 at 1:22 PM, Denys Vitali <notifications@github.com>
wrote:

> +1 @fyless fix worked for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enginespot/js-beautify-sublime/issues/39#issuecomment-171387363>
> .
>



-- 
MSc. Charles M. Romestant F.


Merci de penser à l'environnement avant d'imprimer cet e-mail
Please think about the environment before you print this e-mail
Por favor piense en el medio ambiente antes de imprimir este e-mail

**Comment by Andergraw** [comment] 2016-05-10 12:18
Thank you so much, @ioncube.
Working like a charm

**Comment by mattblang** [comment] 2016-09-16 20:12
@enginespot It seems as though this was fixed at some point between my last comment and now, but recently broke again.

**Comment by enginespot** [comment] 2016-09-25 16:09
@fyelles hmm... can you add a push request to js-beautify , currently I will re architect the plugin.

**Comment by enginespot** [comment] 2016-09-26 15:16
please use the latest verion , it has embed six.py package

**Comment by Roriz** [comment] 2016-09-26 18:36
Thanks @fyelles for the fork, got us working again; can't live without it :)

**Comment by enginespot** [comment] 2016-09-27 14:35
@Roriz hmm... by now, you can use the latest version , it should fix the bug

**Comment by enginespot** [comment] 2016-10-04 14:54
bug fixed with the latest version

**Closed by enginespot** 2016-10-04 14:54 UTC
